export type Difficulty = "Easy" | "Medium" | "Hard";

export interface Question {
  id: string;
  question: string;
  options: string[];
  answer: number; // index 0-3
  explanation: string;
  difficulty: Difficulty;
}

export interface Category {
  slug: string;
  name: string;
  description: string;
  icon: string; // lucide icon name
  accent: string; // tailwind gradient classes
  questions: Question[];
}

const grammar: Question[] = [
  { id: "g1", question: "She ___ to school every day.", options: ["go", "goes", "going", "gone"], answer: 1, explanation: "Use 'goes' with third-person singular subjects.", difficulty: "Easy" },
  { id: "g2", question: "They ___ football every weekend.", options: ["play", "plays", "playing", "played"], answer: 0, explanation: "Use the base verb with the plural subject 'they'.", difficulty: "Easy" },
  { id: "g3", question: "I have lived here ___ five years.", options: ["since", "for", "from", "at"], answer: 1, explanation: "Use 'for' with a period of time.", difficulty: "Easy" },
  { id: "g4", question: "The sun ___ in the east.", options: ["rise", "rises", "rising", "rose"], answer: 1, explanation: "General truths use the simple present tense.", difficulty: "Easy" },
  { id: "g5", question: "She was born ___ July.", options: ["at", "on", "in", "for"], answer: 2, explanation: "Use 'in' with months.", difficulty: "Easy" },
  { id: "g6", question: "He is good ___ mathematics.", options: ["at", "on", "for", "with"], answer: 0, explanation: "The correct phrase is 'good at'.", difficulty: "Easy" },
  { id: "g7", question: "I ___ a movie yesterday.", options: ["see", "saw", "seen", "seeing"], answer: 1, explanation: "The past tense of 'see' is 'saw'.", difficulty: "Easy" },
  { id: "g8", question: "The train had already left when we ___ the station.", options: ["reach", "reached", "reaching", "reaches"], answer: 1, explanation: "The sentence refers to a past event.", difficulty: "Easy" },
  { id: "g9", question: "Would you mind ___ the window?", options: ["close", "closing", "closed", "to close"], answer: 1, explanation: "'Would you mind' is followed by a gerund.", difficulty: "Easy" },
  { id: "g10", question: "She has been working here ___ 2022.", options: ["for", "since", "from", "during"], answer: 1, explanation: "Use 'since' with a specific point in time.", difficulty: "Easy" },
  { id: "g11", question: "The children are playing ___ the park.", options: ["in", "at", "for", "to"], answer: 0, explanation: "We say 'in the park'.", difficulty: "Easy" },
  { id: "g12", question: "Neither of the boys ___ present.", options: ["are", "is", "were", "have"], answer: 1, explanation: "'Neither' takes a singular verb.", difficulty: "Easy" },
  { id: "g13", question: "She can speak French ___ English.", options: ["besides", "beside", "under", "below"], answer: 0, explanation: "'Besides' means 'in addition to'.", difficulty: "Easy" },
  { id: "g14", question: "The meeting was cancelled ___ heavy rain.", options: ["because", "because of", "since", "although"], answer: 1, explanation: "'Because of' is followed by a noun phrase.", difficulty: "Easy" },
  { id: "g15", question: "I am looking forward to ___ you.", options: ["see", "seeing", "saw", "seen"], answer: 1, explanation: "'Look forward to' is followed by a gerund.", difficulty: "Easy" },
  { id: "g16", question: "She ___ her homework before dinner.", options: ["complete", "completes", "completing", "completed"], answer: 1, explanation: "Third-person singular subjects take verbs ending in -s.", difficulty: "Easy" },
  { id: "g17", question: "The teacher asked us ___ quietly.", options: ["sit", "to sit", "sitting", "sat"], answer: 1, explanation: "'Asked' is followed by an infinitive.", difficulty: "Easy" },
  { id: "g18", question: "He apologized ___ being late.", options: ["for", "to", "at", "with"], answer: 0, explanation: "The correct phrase is 'apologized for'.", difficulty: "Easy" },
  { id: "g19", question: "The cake was ___ by my mother.", options: ["make", "made", "making", "makes"], answer: 1, explanation: "The passive voice requires the past participle.", difficulty: "Easy" },
  { id: "g20", question: "If I ___ rich, I would travel the world.", options: ["am", "was", "were", "be"], answer: 2, explanation: "Use 'were' in hypothetical situations.", difficulty: "Easy" },
  { id: "g21", question: "She is interested ___ learning Spanish.", options: ["on", "in", "at", "for"], answer: 1, explanation: "The correct phrase is 'interested in'.", difficulty: "Easy" },
  { id: "g22", question: "The students ___ studying for their exams.", options: ["is", "are", "was", "has"], answer: 1, explanation: "The plural subject 'students' takes 'are'.", difficulty: "Easy" },
  { id: "g23", question: "I have never ___ such a beautiful painting.", options: ["see", "saw", "seen", "seeing"], answer: 2, explanation: "Present perfect uses the past participle.", difficulty: "Easy" },
  { id: "g24", question: "The baby is sleeping ___ the bed.", options: ["on", "in", "under", "over"], answer: 0, explanation: "We normally say 'on the bed'.", difficulty: "Easy" },
  { id: "g25", question: "He ___ to the gym every morning.", options: ["go", "goes", "going", "gone"], answer: 1, explanation: "Third-person singular subjects take verbs ending in -s.", difficulty: "Easy" },
  { id: "g26", question: "The movie starts ___ 7 PM.", options: ["on", "in", "at", "for"], answer: 2, explanation: "Use 'at' for specific times.", difficulty: "Easy" },
  { id: "g27", question: "They have been friends ___ childhood.", options: ["for", "since", "from", "during"], answer: 1, explanation: "Use 'since' with a starting point.", difficulty: "Easy" },
  { id: "g28", question: "My brother is taller ___ me.", options: ["than", "then", "that", "from"], answer: 0, explanation: "Use 'than' in comparisons.", difficulty: "Easy" },
  { id: "g29", question: "She ___ her keys and couldn't find them.", options: ["lose", "lost", "loses", "losing"], answer: 1, explanation: "The sentence refers to a past event.", difficulty: "Easy" },
  { id: "g30", question: "The teacher told us ___ our books.", options: ["open", "opened", "to open", "opening"], answer: 2, explanation: "'Told' is followed by an infinitive.", difficulty: "Easy" },
  { id: "g31", question: "The cat jumped ___ the wall.", options: ["over", "under", "between", "inside"], answer: 0, explanation: "The cat moved across the wall.", difficulty: "Easy" },
  { id: "g32", question: "He is afraid ___ spiders.", options: ["of", "from", "with", "for"], answer: 0, explanation: "The correct phrase is 'afraid of'.", difficulty: "Easy" },
  { id: "g33", question: "I will call you when I ___ home.", options: ["get", "got", "getting", "gets"], answer: 0, explanation: "Use the simple present after 'when' for future meaning.", difficulty: "Easy" },
  { id: "g34", question: "The children were excited ___ the trip.", options: ["about", "with", "from", "under"], answer: 0, explanation: "The correct phrase is 'excited about'.", difficulty: "Medium" },
  { id: "g35", question: "This book is ___ interesting than the last one.", options: ["more", "most", "much", "many"], answer: 0, explanation: "Comparative form is needed.", difficulty: "Medium" },
  { id: "g36", question: "She has already ___ her lunch.", options: ["eat", "eaten", "ate", "eating"], answer: 1, explanation: "Present perfect requires the past participle.", difficulty: "Medium" },
  { id: "g37", question: "There aren't ___ apples left.", options: ["some", "many", "much", "any"], answer: 1, explanation: "'Many' is used with countable plural nouns.", difficulty: "Medium" },
  { id: "g38", question: "The meeting lasted ___ two hours.", options: ["for", "since", "at", "on"], answer: 0, explanation: "Use 'for' with a duration.", difficulty: "Medium" },
  { id: "g39", question: "He prefers tea ___ coffee.", options: ["than", "to", "with", "over"], answer: 1, explanation: "The correct phrase is 'prefer A to B'.", difficulty: "Medium" },
  { id: "g40", question: "We were tired, ___ we continued working.", options: ["but", "because", "if", "so"], answer: 0, explanation: "'But' shows contrast between the two clauses.", difficulty: "Medium" },
  { id: "g41", question: "The teacher explained the lesson ___ detail.", options: ["on", "at", "in", "for"], answer: 2, explanation: "The correct phrase is 'in detail'.", difficulty: "Medium" },
  { id: "g42", question: "She is the ___ student in the class.", options: ["smart", "smarter", "smartest", "more smart"], answer: 2, explanation: "Use the superlative form when comparing with all others.", difficulty: "Medium" },
  { id: "g43", question: "Neither John nor his friends ___ coming today.", options: ["is", "was", "are", "has"], answer: 2, explanation: "The verb agrees with the nearest subject 'friends'.", difficulty: "Medium" },
  { id: "g44", question: "I couldn't attend the meeting ___ I was sick.", options: ["although", "because", "unless", "while"], answer: 1, explanation: "'Because' gives the reason.", difficulty: "Medium" },
  { id: "g45", question: "The children are looking forward to ___ the zoo.", options: ["visit", "visiting", "visited", "visits"], answer: 1, explanation: "'Look forward to' is followed by a gerund.", difficulty: "Medium" },
  { id: "g46", question: "He has been waiting ___ two hours.", options: ["since", "for", "from", "during"], answer: 1, explanation: "Use 'for' with a period of time.", difficulty: "Medium" },
  { id: "g47", question: "The book was written ___ a famous author.", options: ["with", "by", "from", "through"], answer: 1, explanation: "Passive voice uses 'by' to indicate the doer.", difficulty: "Medium" },
  { id: "g48", question: "She speaks English ___ than her sister.", options: ["good", "better", "best", "well"], answer: 1, explanation: "Comparative form is required.", difficulty: "Medium" },
  { id: "g49", question: "The students were asked ___ silent.", options: ["remain", "remaining", "to remain", "remained"], answer: 2, explanation: "'Asked' is followed by an infinitive.", difficulty: "Medium" },
  { id: "g50", question: "I have known him ___ many years.", options: ["since", "for", "from", "at"], answer: 1, explanation: "Use 'for' with a duration.", difficulty: "Medium" },
  { id: "g51", question: "The train arrived ___ time.", options: ["at", "on", "in", "for"], answer: 1, explanation: "The phrase is 'on time'.", difficulty: "Medium" },
  { id: "g52", question: "She insisted ___ paying the bill.", options: ["on", "at", "for", "to"], answer: 0, explanation: "The correct phrase is 'insist on'.", difficulty: "Medium" },
  { id: "g53", question: "If it rains tomorrow, we ___ stay indoors.", options: ["will", "would", "have", "had"], answer: 0, explanation: "First conditional uses 'will' in the main clause.", difficulty: "Medium" },
  { id: "g54", question: "The room was too small ___ everyone.", options: ["fit", "to fit", "fitting", "fits"], answer: 1, explanation: "'Too...to' is the correct structure.", difficulty: "Medium" },
  { id: "g55", question: "He succeeded ___ passing the examination.", options: ["at", "in", "on", "with"], answer: 1, explanation: "The phrase is 'succeed in'.", difficulty: "Medium" },
  { id: "g56", question: "My father ___ in this company since 2015.", options: ["works", "worked", "has worked", "working"], answer: 2, explanation: "Present perfect is used with 'since'.", difficulty: "Medium" },
  { id: "g57", question: "There is ___ water in the bottle.", options: ["many", "few", "much", "little"], answer: 3, explanation: "'Little' is used for an insufficient amount of uncountable nouns.", difficulty: "Medium" },
  { id: "g58", question: "The movie was ___ interesting that everyone enjoyed it.", options: ["so", "too", "very", "much"], answer: 0, explanation: "The structure is 'so...that'.", difficulty: "Medium" },
  { id: "g59", question: "She was absent ___ school yesterday.", options: ["from", "at", "in", "for"], answer: 0, explanation: "The phrase is 'absent from'.", difficulty: "Medium" },
  { id: "g60", question: "The manager asked the employees ___ harder.", options: ["work", "working", "to work", "worked"], answer: 2, explanation: "'Asked' is followed by an infinitive.", difficulty: "Medium" },
  { id: "g61", question: "She is proud ___ her achievements.", options: ["of", "for", "with", "at"], answer: 0, explanation: "The correct phrase is 'proud of'.", difficulty: "Medium" },
  { id: "g62", question: "The children were playing ___ the garden.", options: ["in", "on", "at", "for"], answer: 0, explanation: "We usually say 'in the garden'.", difficulty: "Medium" },
  { id: "g63", question: "I wish I ___ more free time.", options: ["have", "had", "having", "has"], answer: 1, explanation: "Use the past tense after 'wish' for present unreal situations.", difficulty: "Medium" },
  { id: "g64", question: "The shop closes ___ 9 PM every day.", options: ["on", "in", "at", "for"], answer: 2, explanation: "Use 'at' for specific times.", difficulty: "Medium" },
  { id: "g65", question: "She was tired, ___ she finished the project.", options: ["but", "because", "or", "if"], answer: 0, explanation: "But is used to show contrast.", difficulty: "Medium" },
  { id: "g66", question: "The students have ___ completed the assignment.", options: ["yet", "already", "still", "justly"], answer: 1, explanation: "'Already' is used for completed actions.", difficulty: "Medium" },
  { id: "g67", question: "He is married ___ a doctor.", options: ["with", "to", "for", "at"], answer: 1, explanation: "The phrase is 'married to'.", difficulty: "Hard" },
  { id: "g68", question: "The meeting will begin ___ a few minutes.", options: ["on", "at", "in", "for"], answer: 2, explanation: "Use 'in' for future time periods.", difficulty: "Hard" },
  { id: "g69", question: "She asked me ___ I could help her.", options: ["what", "if", "which", "where"], answer: 1, explanation: "'If' introduces an indirect yes/no question.", difficulty: "Hard" },
  { id: "g70", question: "The boy was punished ___ breaking the rules.", options: ["for", "to", "with", "at"], answer: 0, explanation: "The phrase is 'punished for'.", difficulty: "Hard" },
  { id: "g71", question: "He has never ___ abroad before.", options: ["go", "went", "gone", "going"], answer: 2, explanation: "Present perfect uses the past participle.", difficulty: "Hard" },
  { id: "g72", question: "The teacher spoke ___ enough for everyone to hear.", options: ["loud", "loudly", "louder", "loudest"], answer: 1, explanation: "An adverb is needed to describe the verb 'spoke'.", difficulty: "Hard" },
  { id: "g73", question: "We arrived ___ the airport early.", options: ["in", "on", "at", "to"], answer: 2, explanation: "The phrase is 'at the airport'.", difficulty: "Hard" },
  { id: "g74", question: "The book is ___ the table.", options: ["on", "in", "under", "between"], answer: 0, explanation: "The object rests on the table.", difficulty: "Hard" },
  { id: "g75", question: "He promised ___ me tomorrow.", options: ["call", "calling", "to call", "called"], answer: 2, explanation: "'Promise' is followed by an infinitive.", difficulty: "Hard" },
  { id: "g76", question: "The weather is getting ___ every day.", options: ["cold", "colder", "coldest", "more cold"], answer: 1, explanation: "Comparative form is needed.", difficulty: "Hard" },
  { id: "g77", question: "Neither of the answers ___ correct.", options: ["are", "were", "is", "have"], answer: 2, explanation: "'Neither' takes a singular verb.", difficulty: "Hard" },
  { id: "g78", question: "The company specializes ___ software development.", options: ["in", "on", "at", "for"], answer: 0, explanation: "The phrase is 'specializes in'.", difficulty: "Hard" },
  { id: "g79", question: "She has lived here ___ she was a child.", options: ["for", "since", "from", "during"], answer: 1, explanation: "Use 'since' with a starting point.", difficulty: "Hard" },
  { id: "g80", question: "The teacher encouraged us ___ harder.", options: ["study", "studying", "to study", "studied"], answer: 2, explanation: "'Encourage' is followed by an infinitive.", difficulty: "Hard" },
  { id: "g81", question: "The manager congratulated her ___ winning the award.", options: ["for", "to", "at", "with"], answer: 0, explanation: "The phrase is 'congratulated her for'.", difficulty: "Hard" },
  { id: "g82", question: "I don't have ___ money left.", options: ["many", "few", "much", "some"], answer: 2, explanation: "'Much' is used with uncountable nouns.", difficulty: "Hard" },
  { id: "g83", question: "The children were excited ___ their vacation.", options: ["about", "at", "from", "for"], answer: 0, explanation: "The phrase is 'excited about'.", difficulty: "Hard" },
  { id: "g84", question: "She was absent ___ work yesterday.", options: ["from", "at", "to", "for"], answer: 0, explanation: "The phrase is 'absent from'.", difficulty: "Hard" },
  { id: "g85", question: "The teacher made the students ___ the essay again.", options: ["write", "writing", "to write", "wrote"], answer: 0, explanation: "'Make' is followed by the base verb.", difficulty: "Hard" },
  { id: "g86", question: "He is one of the best players who ___ ever played here.", options: ["has", "have", "was", "is"], answer: 1, explanation: "The verb agrees with 'players' (plural).", difficulty: "Hard" },
  { id: "g87", question: "The train was delayed ___ bad weather.", options: ["because", "because of", "although", "despite"], answer: 1, explanation: "'Because of' is followed by a noun phrase.", difficulty: "Hard" },
  { id: "g88", question: "I am not accustomed ___ working at night.", options: ["to", "for", "with", "on"], answer: 0, explanation: "The phrase is 'accustomed to'.", difficulty: "Hard" },
  { id: "g89", question: "The baby stopped ___ when it saw its mother.", options: ["cry", "crying", "cried", "to cry"], answer: 1, explanation: "'Stopped crying' means the action ended.", difficulty: "Hard" },
  { id: "g90", question: "There were ___ people at the concert than expected.", options: ["more", "most", "many", "much"], answer: 0, explanation: "A comparison requires the comparative form.", difficulty: "Hard" },
  { id: "g91", question: "She apologized ___ the misunderstanding.", options: ["for", "to", "at", "on"], answer: 0, explanation: "The phrase is 'apologized for'.", difficulty: "Hard" },
  { id: "g92", question: "The report must be submitted ___ Friday.", options: ["by", "at", "for", "on"], answer: 0, explanation: "'By Friday' means no later than Friday.", difficulty: "Hard" },
  { id: "g93", question: "He is capable ___ solving difficult problems.", options: ["for", "with", "of", "at"], answer: 2, explanation: "The phrase is 'capable of'.", difficulty: "Hard" },
  { id: "g94", question: "The meeting was postponed ___ next week.", options: ["until", "since", "during", "at"], answer: 0, explanation: "'Until next week' indicates the new time.", difficulty: "Hard" },
  { id: "g95", question: "I wish I ___ how to play the piano.", options: ["know", "knew", "knowing", "known"], answer: 1, explanation: "Use the past tense after 'wish'.", difficulty: "Hard" },
  { id: "g96", question: "The students succeeded ___ completing the project.", options: ["at", "with", "in", "for"], answer: 2, explanation: "The phrase is 'succeeded in'.", difficulty: "Hard" },
  { id: "g97", question: "She is taller ___ her older sister.", options: ["than", "then", "that", "from"], answer: 0, explanation: "Comparisons use 'than'.", difficulty: "Hard" },
  { id: "g98", question: "The old building was destroyed ___ a fire.", options: ["with", "from", "by", "at"], answer: 2, explanation: "Passive voice uses 'by' to indicate the cause.", difficulty: "Hard" },
  { id: "g99", question: "He asked me where I ___ the book.", options: ["buy", "bought", "buying", "buys"], answer: 1, explanation: "Reported speech refers to a past action.", difficulty: "Hard" },
  { id: "g100", question: "The company plans ___ a new office next year.", options: ["open", "opening", "to open", "opened"], answer: 2, explanation: "'Plan' is followed by an infinitive.", difficulty: "Hard" },
];

const vocabulary: Question[] = [
  { id: "v1", question: "What does 'abundant' mean?", options: ["Scarce", "Plentiful", "Tiny", "Weak"], answer: 1, explanation: "Abundant means existing in large quantities.", difficulty: "Easy" },
  { id: "v2", question: "What does 'cautious' mean?", options: ["Careful", "Angry", "Lazy", "Fearless"], answer: 0, explanation: "Cautious means being careful to avoid danger or mistakes.", difficulty: "Easy" },
  { id: "v3", question: "What does 'generous' mean?", options: ["Selfish", "Kind and giving", "Poor", "Strict"], answer: 1, explanation: "A generous person is willing to give or share.", difficulty: "Easy" },
  { id: "v4", question: "What does 'fragile' mean?", options: ["Strong", "Heavy", "Easily broken", "Expensive"], answer: 2, explanation: "Fragile objects can break easily.", difficulty: "Easy" },
  { id: "v5", question: "What does 'ancient' mean?", options: ["Modern", "Very old", "Beautiful", "Rare"], answer: 1, explanation: "Ancient refers to something extremely old.", difficulty: "Easy" },
  { id: "v6", question: "What does 'diligent' mean?", options: ["Hardworking", "Lazy", "Rude", "Funny"], answer: 0, explanation: "Diligent means showing effort and care in work.", difficulty: "Easy" },
  { id: "v7", question: "What does 'reluctant' mean?", options: ["Eager", "Unwilling", "Excited", "Curious"], answer: 1, explanation: "Reluctant means not wanting to do something.", difficulty: "Easy" },
  { id: "v8", question: "What does 'vivid' mean?", options: ["Dull", "Bright and clear", "Small", "Weak"], answer: 1, explanation: "Vivid describes something very clear and detailed.", difficulty: "Easy" },
  { id: "v9", question: "What does 'humble' mean?", options: ["Proud", "Modest", "Rich", "Famous"], answer: 1, explanation: "A humble person does not boast.", difficulty: "Easy" },
  { id: "v10", question: "What does 'swift' mean?", options: ["Slow", "Fast", "Heavy", "Quiet"], answer: 1, explanation: "Swift means moving quickly.", difficulty: "Easy" },
  { id: "v11", question: "What does 'obsolete' mean?", options: ["New", "Outdated", "Useful", "Popular"], answer: 1, explanation: "Obsolete means no longer in use.", difficulty: "Easy" },
  { id: "v12", question: "What does 'transparent' mean?", options: ["Dark", "See-through", "Hard", "Heavy"], answer: 1, explanation: "Transparent materials allow light to pass through.", difficulty: "Easy" },
  { id: "v13", question: "What does 'hostile' mean?", options: ["Friendly", "Aggressive", "Funny", "Helpful"], answer: 1, explanation: "Hostile means unfriendly or antagonistic.", difficulty: "Easy" },
  { id: "v14", question: "What does 'fortunate' mean?", options: ["Lucky", "Poor", "Sad", "Careless"], answer: 0, explanation: "Fortunate means having good luck.", difficulty: "Easy" },
  { id: "v15", question: "What does 'scarce' mean?", options: ["Abundant", "Rare", "Heavy", "Cheap"], answer: 1, explanation: "Scarce means available in small amounts.", difficulty: "Easy" },
  { id: "v16", question: "What does 'precise' mean?", options: ["Accurate", "Confusing", "Large", "Messy"], answer: 0, explanation: "Precise means exact and accurate.", difficulty: "Easy" },
  { id: "v17", question: "What does 'adapt' mean?", options: ["Refuse", "Adjust", "Destroy", "Forget"], answer: 1, explanation: "Adapt means to change to fit new conditions.", difficulty: "Easy" },
  { id: "v18", question: "What does 'grateful' mean?", options: ["Thankful", "Angry", "Hungry", "Busy"], answer: 0, explanation: "Grateful means feeling appreciation.", difficulty: "Easy" },
  { id: "v19", question: "What does 'expand' mean?", options: ["Shrink", "Grow larger", "Hide", "Break"], answer: 1, explanation: "Expand means to increase in size.", difficulty: "Easy" },
  { id: "v20", question: "What does 'temporary' mean?", options: ["Permanent", "Short-term", "Dangerous", "Ancient"], answer: 1, explanation: "Temporary means lasting for a limited time.", difficulty: "Easy" },
  { id: "v21", question: "What does 'brilliant' mean?", options: ["Dull", "Intelligent", "Weak", "Careless"], answer: 1, explanation: "Brilliant often means highly intelligent or exceptionally talented.", difficulty: "Easy" },
  { id: "v22", question: "What does 'vanish' mean?", options: ["Appear", "Disappear", "Grow", "Remain"], answer: 1, explanation: "Vanish means to disappear suddenly.", difficulty: "Easy" },
  { id: "v23", question: "What does 'eager' mean?", options: ["Uninterested", "Excited and willing", "Angry", "Confused"], answer: 1, explanation: "Eager means enthusiastic about doing something.", difficulty: "Easy" },
  { id: "v24", question: "What does 'loyal' mean?", options: ["Faithful", "Dishonest", "Cruel", "Lazy"], answer: 0, explanation: "A loyal person remains faithful and supportive.", difficulty: "Easy" },
  { id: "v25", question: "What does 'brief' mean?", options: ["Long", "Short", "Expensive", "Complicated"], answer: 1, explanation: "Brief means lasting a short time.", difficulty: "Easy" },
  { id: "v26", question: "What does 'sincere' mean?", options: ["Honest", "Fake", "Funny", "Proud"], answer: 0, explanation: "Sincere means genuine and honest.", difficulty: "Easy" },
  { id: "v27", question: "What does 'vast' mean?", options: ["Tiny", "Huge", "Narrow", "Weak"], answer: 1, explanation: "Vast means extremely large.", difficulty: "Easy" },
  { id: "v28", question: "What does 'timid' mean?", options: ["Brave", "Shy", "Strong", "Smart"], answer: 1, explanation: "Timid means lacking confidence or courage.", difficulty: "Easy" },
  { id: "v29", question: "What does 'reliable' mean?", options: ["Trustworthy", "Lazy", "Dangerous", "Weak"], answer: 0, explanation: "Reliable means dependable.", difficulty: "Easy" },
  { id: "v30", question: "What does 'dense' mean?", options: ["Thin", "Thick", "Fast", "Expensive"], answer: 1, explanation: "Dense means closely packed together.", difficulty: "Easy" },
  { id: "v31", question: "What does 'generally' mean?", options: ["Usually", "Never", "Rarely", "Suddenly"], answer: 0, explanation: "Generally means in most cases.", difficulty: "Easy" },
  { id: "v32", question: "What does 'frequent' mean?", options: ["Rare", "Occasional", "Happening often", "Difficult"], answer: 2, explanation: "Frequent means occurring repeatedly.", difficulty: "Easy" },
  { id: "v33", question: "What does 'confident' mean?", options: ["Certain", "Afraid", "Weak", "Unsure"], answer: 0, explanation: "Confident means feeling sure about something.", difficulty: "Easy" },
  { id: "v34", question: "What does 'resist' mean?", options: ["Accept", "Oppose", "Ignore", "Encourage"], answer: 1, explanation: "Resist means to fight against something.", difficulty: "Medium" },
  { id: "v35", question: "What does 'generous' mean?", options: ["Kind and giving", "Selfish", "Greedy", "Angry"], answer: 0, explanation: "Generous people willingly share with others.", difficulty: "Medium" },
  { id: "v36", question: "What does 'endure' mean?", options: ["Suffer patiently", "Celebrate", "Forget", "Refuse"], answer: 0, explanation: "Endure means to tolerate hardship.", difficulty: "Medium" },
  { id: "v37", question: "What does 'minor' mean?", options: ["Major", "Small", "Ancient", "Important"], answer: 1, explanation: "Minor means less important or smaller.", difficulty: "Medium" },
  { id: "v38", question: "What does 'scarcity' mean?", options: ["Abundance", "Shortage", "Happiness", "Growth"], answer: 1, explanation: "Scarcity means a lack of something.", difficulty: "Medium" },
  { id: "v39", question: "What does 'modify' mean?", options: ["Destroy", "Change", "Hide", "Lose"], answer: 1, explanation: "Modify means to alter or adjust.", difficulty: "Medium" },
  { id: "v40", question: "What does 'extraordinary' mean?", options: ["Ordinary", "Remarkable", "Common", "Average"], answer: 1, explanation: "Extraordinary means very unusual or impressive.", difficulty: "Medium" },
  { id: "v41", question: "What does 'astonish' mean?", options: ["Bore", "Surprise greatly", "Hide", "Forget"], answer: 1, explanation: "Astonish means to surprise someone very much.", difficulty: "Medium" },
  { id: "v42", question: "What does 'benevolent' mean?", options: ["Kind", "Cruel", "Lazy", "Silent"], answer: 0, explanation: "Benevolent means well-meaning and kind.", difficulty: "Medium" },
  { id: "v43", question: "What does 'commence' mean?", options: ["Finish", "Begin", "Delay", "Stop"], answer: 1, explanation: "Commence means to start something.", difficulty: "Medium" },
  { id: "v44", question: "What does 'deteriorate' mean?", options: ["Improve", "Worsen", "Repair", "Expand"], answer: 1, explanation: "Deteriorate means to become worse.", difficulty: "Medium" },
  { id: "v45", question: "What does 'eliminate' mean?", options: ["Remove", "Add", "Protect", "Ignore"], answer: 0, explanation: "Eliminate means to completely remove.", difficulty: "Medium" },
  { id: "v46", question: "What does 'foster' mean?", options: ["Discourage", "Encourage growth", "Destroy", "Forget"], answer: 1, explanation: "Foster means to support development.", difficulty: "Medium" },
  { id: "v47", question: "What does 'genuine' mean?", options: ["Fake", "Real", "Weak", "Rare"], answer: 1, explanation: "Genuine means authentic or real.", difficulty: "Medium" },
  { id: "v48", question: "What does 'hinder' mean?", options: ["Help", "Delay", "Reward", "Promote"], answer: 1, explanation: "Hinder means to create difficulties or delays.", difficulty: "Medium" },
  { id: "v49", question: "What does 'immense' mean?", options: ["Tiny", "Extremely large", "Fragile", "Light"], answer: 1, explanation: "Immense means huge in size.", difficulty: "Medium" },
  { id: "v50", question: "What does 'justify' mean?", options: ["Blame", "Prove right", "Hide", "Ignore"], answer: 1, explanation: "Justify means to show that something is reasonable.", difficulty: "Medium" },
  { id: "v51", question: "What does 'keen' mean?", options: ["Interested", "Bored", "Weak", "Careless"], answer: 0, explanation: "Keen means eager or interested.", difficulty: "Medium" },
  { id: "v52", question: "What does 'liberate' mean?", options: ["Capture", "Free", "Punish", "Hide"], answer: 1, explanation: "Liberate means to set free.", difficulty: "Medium" },
  { id: "v53", question: "What does 'mandatory' mean?", options: ["Optional", "Required", "Dangerous", "Temporary"], answer: 1, explanation: "Mandatory means required by rule.", difficulty: "Medium" },
  { id: "v54", question: "What does 'notable' mean?", options: ["Unimportant", "Remarkable", "Ordinary", "Silent"], answer: 1, explanation: "Notable means worthy of attention.", difficulty: "Medium" },
  { id: "v55", question: "What does 'obtain' mean?", options: ["Lose", "Acquire", "Destroy", "Forget"], answer: 1, explanation: "Obtain means to get something.", difficulty: "Medium" },
  { id: "v56", question: "What does 'perceive' mean?", options: ["Notice", "Ignore", "Hide", "Reject"], answer: 0, explanation: "Perceive means to become aware of.", difficulty: "Medium" },
  { id: "v57", question: "What does 'quit' mean?", options: ["Continue", "Stop", "Expand", "Repair"], answer: 1, explanation: "Quit means to stop doing something.", difficulty: "Medium" },
  { id: "v58", question: "What does 'retain' mean?", options: ["Forget", "Keep", "Remove", "Break"], answer: 1, explanation: "Retain means to continue having something.", difficulty: "Medium" },
  { id: "v59", question: "What does 'sufficient' mean?", options: ["Enough", "Scarce", "Huge", "Weak"], answer: 0, explanation: "Sufficient means adequate or enough.", difficulty: "Medium" },
  { id: "v60", question: "What does 'terminate' mean?", options: ["Start", "End", "Improve", "Repair"], answer: 1, explanation: "Terminate means to bring something to an end.", difficulty: "Medium" },
  { id: "v61", question: "What does 'abandon' mean?", options: ["Keep", "Leave behind", "Repair", "Protect"], answer: 1, explanation: "Abandon means to leave something or someone behind.", difficulty: "Hard" },
  { id: "v62", question: "What does 'accurate' mean?", options: ["Incorrect", "Exact", "Difficult", "Temporary"], answer: 1, explanation: "Accurate means correct and precise.", difficulty: "Hard" },
  { id: "v63", question: "What does 'ambitious' mean?", options: ["Lazy", "Having strong goals", "Weak", "Careless"], answer: 1, explanation: "Ambitious people are determined to achieve success.", difficulty: "Hard" },
  { id: "v64", question: "What does 'appreciate' mean?", options: ["Ignore", "Value", "Destroy", "Refuse"], answer: 1, explanation: "Appreciate means to recognize the worth of something.", difficulty: "Hard" },
  { id: "v65", question: "What does 'arduous' mean?", options: ["Easy", "Difficult", "Funny", "Short"], answer: 1, explanation: "Arduous means requiring a lot of effort.", difficulty: "Hard" },
  { id: "v66", question: "What does 'assume' mean?", options: ["Question", "Suppose", "Reject", "Forget"], answer: 1, explanation: "Assume means to believe something without proof.", difficulty: "Hard" },
  { id: "v67", question: "What does 'authentic' mean?", options: ["Fake", "Genuine", "Broken", "Rare"], answer: 1, explanation: "Authentic means real and original.", difficulty: "Hard" },
  { id: "v68", question: "What does 'awkward' mean?", options: ["Comfortable", "Uncomfortable", "Strong", "Exciting"], answer: 1, explanation: "Awkward describes an uncomfortable situation.", difficulty: "Hard" },
  { id: "v69", question: "What does 'beneficial' mean?", options: ["Harmful", "Helpful", "Expensive", "Temporary"], answer: 1, explanation: "Beneficial means producing good results.", difficulty: "Hard" },
  { id: "v70", question: "What does 'calculate' mean?", options: ["Estimate mathematically", "Destroy", "Forget", "Delay"], answer: 0, explanation: "Calculate means to determine using mathematics.", difficulty: "Hard" },
  { id: "v71", question: "What does 'capable' mean?", options: ["Unable", "Able", "Weak", "Confused"], answer: 1, explanation: "Capable means having the ability to do something.", difficulty: "Hard" },
  { id: "v72", question: "What does 'clarify' mean?", options: ["Confuse", "Explain clearly", "Hide", "Reject"], answer: 1, explanation: "Clarify means to make something easier to understand.", difficulty: "Hard" },
  { id: "v73", question: "What does 'cooperate' mean?", options: ["Argue", "Work together", "Compete", "Ignore"], answer: 1, explanation: "Cooperate means to work jointly toward a goal.", difficulty: "Hard" },
  { id: "v74", question: "What does 'crucial' mean?", options: ["Unimportant", "Extremely important", "Funny", "Cheap"], answer: 1, explanation: "Crucial means very important.", difficulty: "Hard" },
  { id: "v75", question: "What does 'decline' mean?", options: ["Increase", "Refuse or decrease", "Accept", "Repair"], answer: 1, explanation: "Decline can mean to refuse or become less.", difficulty: "Hard" },
  { id: "v76", question: "What does 'dedicate' mean?", options: ["Commit", "Avoid", "Forget", "Hide"], answer: 0, explanation: "Dedicate means to devote yourself to something.", difficulty: "Hard" },
  { id: "v77", question: "What does 'efficient' mean?", options: ["Wasteful", "Productive", "Slow", "Confused"], answer: 1, explanation: "Efficient means achieving results with minimal waste.", difficulty: "Hard" },
  { id: "v78", question: "What does 'encounter' mean?", options: ["Avoid", "Meet unexpectedly", "Hide", "Lose"], answer: 1, explanation: "Encounter means to come across something unexpectedly.", difficulty: "Hard" },
  { id: "v79", question: "What does 'essential' mean?", options: ["Optional", "Necessary", "Rare", "Expensive"], answer: 1, explanation: "Essential means absolutely necessary.", difficulty: "Hard" },
  { id: "v80", question: "What does 'evaluate' mean?", options: ["Ignore", "Assess", "Destroy", "Hide"], answer: 1, explanation: "Evaluate means to judge or determine value.", difficulty: "Hard" },
  { id: "v81", question: "What does 'flourish' mean?", options: ["Decline", "Prosper", "Hide", "Fail"], answer: 1, explanation: "Flourish means to grow or develop successfully.", difficulty: "Hard" },
  { id: "v82", question: "What does 'frequent' mean?", options: ["Rare", "Occurring often", "Expensive", "Difficult"], answer: 1, explanation: "Frequent means happening repeatedly.", difficulty: "Hard" },
  { id: "v83", question: "What does 'graceful' mean?", options: ["Clumsy", "Elegant", "Loud", "Rude"], answer: 1, explanation: "Graceful means moving in a smooth and attractive way.", difficulty: "Hard" },
  { id: "v84", question: "What does 'hesitate' mean?", options: ["Act quickly", "Pause before acting", "Celebrate", "Ignore"], answer: 1, explanation: "Hesitate means to be uncertain before doing something.", difficulty: "Hard" },
  { id: "v85", question: "What does 'identical' mean?", options: ["Different", "Exactly the same", "Broken", "Rare"], answer: 1, explanation: "Identical means completely alike.", difficulty: "Hard" },
  { id: "v86", question: "What does 'illustrate' mean?", options: ["Confuse", "Explain with examples", "Hide", "Destroy"], answer: 1, explanation: "Illustrate means to make something clear through examples.", difficulty: "Hard" },
  { id: "v87", question: "What does 'inspire' mean?", options: ["Discourage", "Motivate", "Ignore", "Delay"], answer: 1, explanation: "Inspire means to encourage someone to do something.", difficulty: "Hard" },
  { id: "v88", question: "What does 'investigate' mean?", options: ["Ignore", "Examine carefully", "Hide", "Forget"], answer: 1, explanation: "Investigate means to look into something thoroughly.", difficulty: "Hard" },
  { id: "v89", question: "What does 'justify' mean?", options: ["Condemn", "Give reasons for", "Destroy", "Avoid"], answer: 1, explanation: "Justify means to show that something is reasonable.", difficulty: "Hard" },
  { id: "v90", question: "What does 'keen' mean?", options: ["Interested", "Bored", "Weak", "Angry"], answer: 0, explanation: "Keen means eager or enthusiastic.", difficulty: "Hard" },
  { id: "v91", question: "What does 'legitimate' mean?", options: ["Illegal", "Lawful", "Rare", "Temporary"], answer: 1, explanation: "Legitimate means lawful or valid.", difficulty: "Hard" },
  { id: "v92", question: "What does 'maintain' mean?", options: ["Abandon", "Keep in good condition", "Destroy", "Forget"], answer: 1, explanation: "Maintain means to preserve or continue.", difficulty: "Hard" },
  { id: "v93", question: "What does 'navigate' mean?", options: ["Get lost", "Find a route", "Sleep", "Hide"], answer: 1, explanation: "Navigate means to plan and follow a path.", difficulty: "Hard" },
  { id: "v94", question: "What does 'obstacle' mean?", options: ["Advantage", "Barrier", "Reward", "Solution"], answer: 1, explanation: "An obstacle is something that blocks progress.", difficulty: "Hard" },
  { id: "v95", question: "What does 'persuade' mean?", options: ["Convince", "Ignore", "Punish", "Delay"], answer: 0, explanation: "Persuade means to convince someone.", difficulty: "Hard" },
  { id: "v96", question: "What does 'qualify' mean?", options: ["Become eligible", "Fail", "Ignore", "Destroy"], answer: 0, explanation: "Qualify means to meet the required conditions.", difficulty: "Hard" },
  { id: "v97", question: "What does 'reveal' mean?", options: ["Hide", "Show", "Destroy", "Forget"], answer: 1, explanation: "Reveal means to make known.", difficulty: "Hard" },
  { id: "v98", question: "What does 'significant' mean?", options: ["Unimportant", "Important", "Rare", "Temporary"], answer: 1, explanation: "Significant means important or meaningful.", difficulty: "Hard" },
  { id: "v99", question: "What does 'transform' mean?", options: ["Keep unchanged", "Change completely", "Hide", "Delay"], answer: 1, explanation: "Transform means to change form or appearance.", difficulty: "Hard" },
  { id: "v100", question: "What does 'utilize' mean?", options: ["Waste", "Use", "Ignore", "Destroy"], answer: 1, explanation: "Utilize means to make practical use of something.", difficulty: "Hard" },
];

const synonyms: Question[] = [
  { id: "s1", question: "Choose the synonym of 'Happy'.", options: ["Sad", "Joyful", "Angry", "Weak"], answer: 1, explanation: "Joyful means feeling great happiness.", difficulty: "Easy" },
  { id: "s2", question: "Choose the synonym of 'Brave'.", options: ["Fearful", "Cowardly", "Courageous", "Lazy"], answer: 2, explanation: "Courageous means brave and fearless.", difficulty: "Easy" },
  { id: "s3", question: "Choose the synonym of 'Quick'.", options: ["Slow", "Rapid", "Heavy", "Weak"], answer: 1, explanation: "Rapid means very fast.", difficulty: "Easy" },
  { id: "s4", question: "Choose the synonym of 'Intelligent'.", options: ["Smart", "Dull", "Careless", "Silent"], answer: 0, explanation: "Smart is a synonym of intelligent.", difficulty: "Easy" },
  { id: "s5", question: "Choose the synonym of 'Ancient'.", options: ["Modern", "Old", "Future", "Fresh"], answer: 1, explanation: "Ancient means very old.", difficulty: "Easy" },
  { id: "s6", question: "Choose the synonym of 'Begin'.", options: ["Start", "Finish", "Stop", "Pause"], answer: 0, explanation: "Start and begin have similar meanings.", difficulty: "Easy" },
  { id: "s7", question: "Choose the synonym of 'Large'.", options: ["Tiny", "Huge", "Short", "Thin"], answer: 1, explanation: "Huge means very large.", difficulty: "Easy" },
  { id: "s8", question: "Choose the synonym of 'Silent'.", options: ["Noisy", "Quiet", "Loud", "Busy"], answer: 1, explanation: "Quiet means making little or no noise.", difficulty: "Easy" },
  { id: "s9", question: "Choose the synonym of 'Difficult'.", options: ["Hard", "Easy", "Simple", "Clear"], answer: 0, explanation: "Hard is a synonym of difficult.", difficulty: "Easy" },
  { id: "s10", question: "Choose the synonym of 'Honest'.", options: ["Truthful", "Dishonest", "Rude", "Lazy"], answer: 0, explanation: "Truthful means honest.", difficulty: "Easy" },
  { id: "s11", question: "Choose the synonym of 'Wealthy'.", options: ["Poor", "Rich", "Hungry", "Weak"], answer: 1, explanation: "Rich means wealthy.", difficulty: "Easy" },
  { id: "s12", question: "Choose the synonym of 'Tiny'.", options: ["Huge", "Small", "Wide", "Long"], answer: 1, explanation: "Small is a synonym of tiny.", difficulty: "Easy" },
  { id: "s13", question: "Choose the synonym of 'Beautiful'.", options: ["Ugly", "Pretty", "Dirty", "Weak"], answer: 1, explanation: "Pretty means attractive or beautiful.", difficulty: "Easy" },
  { id: "s14", question: "Choose the synonym of 'Dangerous'.", options: ["Safe", "Risky", "Calm", "Soft"], answer: 1, explanation: "Risky means dangerous.", difficulty: "Easy" },
  { id: "s15", question: "Choose the synonym of 'Correct'.", options: ["Wrong", "Accurate", "False", "Broken"], answer: 1, explanation: "Accurate means correct.", difficulty: "Easy" },
  { id: "s16", question: "Choose the synonym of 'End'.", options: ["Finish", "Start", "Open", "Grow"], answer: 0, explanation: "Finish means to end something.", difficulty: "Easy" },
  { id: "s17", question: "Choose the synonym of 'Assist'.", options: ["Help", "Harm", "Ignore", "Hide"], answer: 0, explanation: "Help is a synonym of assist.", difficulty: "Easy" },
  { id: "s18", question: "Choose the synonym of 'Calm'.", options: ["Peaceful", "Angry", "Wild", "Loud"], answer: 0, explanation: "Peaceful means calm and relaxed.", difficulty: "Easy" },
  { id: "s19", question: "Choose the synonym of 'Purchase'.", options: ["Sell", "Buy", "Lose", "Throw"], answer: 1, explanation: "Purchase means to buy.", difficulty: "Easy" },
  { id: "s20", question: "Choose the synonym of 'Repair'.", options: ["Fix", "Break", "Damage", "Hide"], answer: 0, explanation: "Fix means to repair.", difficulty: "Easy" },
  { id: "s21", question: "Choose the synonym of 'Abundant'.", options: ["Scarce", "Plentiful", "Tiny", "Weak"], answer: 1, explanation: "Plentiful means existing in large amounts.", difficulty: "Easy" },
  { id: "s22", question: "Choose the synonym of 'Admire'.", options: ["Respect", "Hate", "Ignore", "Avoid"], answer: 0, explanation: "Admire means to respect or look up to.", difficulty: "Easy" },
  { id: "s23", question: "Choose the synonym of 'Alert'.", options: ["Sleepy", "Watchful", "Lazy", "Weak"], answer: 1, explanation: "Watchful means alert and attentive.", difficulty: "Easy" },
  { id: "s24", question: "Choose the synonym of 'Arrive'.", options: ["Leave", "Reach", "Escape", "Travel"], answer: 1, explanation: "Reach means to arrive at a destination.", difficulty: "Easy" },
  { id: "s25", question: "Choose the synonym of 'Avoid'.", options: ["Seek", "Evade", "Meet", "Accept"], answer: 1, explanation: "Evade means to avoid something.", difficulty: "Easy" },
  { id: "s26", question: "Choose the synonym of 'Bold'.", options: ["Timid", "Fearless", "Weak", "Quiet"], answer: 1, explanation: "Fearless means bold and brave.", difficulty: "Easy" },
  { id: "s27", question: "Choose the synonym of 'Brief'.", options: ["Long", "Short", "Wide", "Heavy"], answer: 1, explanation: "Brief means lasting a short time.", difficulty: "Easy" },
  { id: "s28", question: "Choose the synonym of 'Capture'.", options: ["Release", "Seize", "Ignore", "Destroy"], answer: 1, explanation: "Seize means to capture.", difficulty: "Easy" },
  { id: "s29", question: "Choose the synonym of 'Clever'.", options: ["Smart", "Dull", "Lazy", "Weak"], answer: 0, explanation: "Smart is a synonym of clever.", difficulty: "Easy" },
  { id: "s30", question: "Choose the synonym of 'Combine'.", options: ["Separate", "Merge", "Break", "Divide"], answer: 1, explanation: "Merge means to combine together.", difficulty: "Easy" },
  { id: "s31", question: "Choose the synonym of 'Create'.", options: ["Destroy", "Produce", "Remove", "Hide"], answer: 1, explanation: "Produce means to create.", difficulty: "Easy" },
  { id: "s32", question: "Choose the synonym of 'Decrease'.", options: ["Increase", "Reduce", "Expand", "Grow"], answer: 1, explanation: "Reduce means to decrease.", difficulty: "Easy" },
  { id: "s33", question: "Choose the synonym of 'Defend'.", options: ["Attack", "Protect", "Ignore", "Leave"], answer: 1, explanation: "Protect means to defend.", difficulty: "Easy" },
  { id: "s34", question: "Choose the synonym of 'Delicate'.", options: ["Strong", "Fragile", "Heavy", "Rough"], answer: 1, explanation: "Fragile means delicate and easily damaged.", difficulty: "Medium" },
  { id: "s35", question: "Choose the synonym of 'Demand'.", options: ["Request", "Refuse", "Ignore", "Offer"], answer: 0, explanation: "Request can be a synonym of demand in many contexts.", difficulty: "Medium" },
  { id: "s36", question: "Choose the synonym of 'Discover'.", options: ["Lose", "Find", "Hide", "Forget"], answer: 1, explanation: "Find means to discover.", difficulty: "Medium" },
  { id: "s37", question: "Choose the synonym of 'Enormous'.", options: ["Tiny", "Massive", "Weak", "Short"], answer: 1, explanation: "Massive means very large.", difficulty: "Medium" },
  { id: "s38", question: "Choose the synonym of 'Essential'.", options: ["Optional", "Necessary", "Rare", "Temporary"], answer: 1, explanation: "Necessary means essential.", difficulty: "Medium" },
  { id: "s39", question: "Choose the synonym of 'Famous'.", options: ["Unknown", "Well-known", "Hidden", "Ordinary"], answer: 1, explanation: "Well-known means famous.", difficulty: "Medium" },
  { id: "s40", question: "Choose the synonym of 'Generous'.", options: ["Kind-hearted", "Selfish", "Greedy", "Cruel"], answer: 0, explanation: "Kind-hearted is a synonym of generous.", difficulty: "Medium" },
  { id: "s41", question: "Choose the synonym of 'Genuine'.", options: ["Fake", "Authentic", "Broken", "Weak"], answer: 1, explanation: "Authentic means genuine or real.", difficulty: "Medium" },
  { id: "s42", question: "Choose the synonym of 'Gradual'.", options: ["Sudden", "Slow", "Instant", "Rapid"], answer: 1, explanation: "Gradual means happening slowly over time.", difficulty: "Medium" },
  { id: "s43", question: "Choose the synonym of 'Harmful'.", options: ["Beneficial", "Damaging", "Helpful", "Safe"], answer: 1, explanation: "Damaging means causing harm.", difficulty: "Medium" },
  { id: "s44", question: "Choose the synonym of 'Hasty'.", options: ["Careful", "Hurried", "Patient", "Slow"], answer: 1, explanation: "Hurried means done quickly.", difficulty: "Medium" },
  { id: "s45", question: "Choose the synonym of 'Idle'.", options: ["Busy", "Inactive", "Energetic", "Productive"], answer: 1, explanation: "Inactive means not active.", difficulty: "Medium" },
  { id: "s46", question: "Choose the synonym of 'Imitate'.", options: ["Create", "Copy", "Destroy", "Ignore"], answer: 1, explanation: "Copy means to imitate.", difficulty: "Medium" },
  { id: "s47", question: "Choose the synonym of 'Increase'.", options: ["Reduce", "Expand", "Shrink", "Cut"], answer: 1, explanation: "Expand means to increase in size or amount.", difficulty: "Medium" },
  { id: "s48", question: "Choose the synonym of 'Infinite'.", options: ["Limited", "Endless", "Tiny", "Short"], answer: 1, explanation: "Endless means infinite.", difficulty: "Medium" },
  { id: "s49", question: "Choose the synonym of 'Journey'.", options: ["Trip", "Home", "Stop", "Delay"], answer: 0, explanation: "Trip is a synonym of journey.", difficulty: "Medium" },
  { id: "s50", question: "Choose the synonym of 'Justice'.", options: ["Fairness", "Corruption", "Crime", "Dishonesty"], answer: 0, explanation: "Fairness is a synonym of justice.", difficulty: "Medium" },
  { id: "s51", question: "Choose the synonym of 'Knowledge'.", options: ["Ignorance", "Understanding", "Confusion", "Mistake"], answer: 1, explanation: "Understanding is closely related to knowledge.", difficulty: "Medium" },
  { id: "s52", question: "Choose the synonym of 'Liberty'.", options: ["Freedom", "Prison", "Control", "Restriction"], answer: 0, explanation: "Freedom means liberty.", difficulty: "Medium" },
  { id: "s53", question: "Choose the synonym of 'Magnify'.", options: ["Reduce", "Enlarge", "Hide", "Shorten"], answer: 1, explanation: "Enlarge means to magnify.", difficulty: "Medium" },
  { id: "s54", question: "Choose the synonym of 'Noble'.", options: ["Honorable", "Cruel", "Greedy", "Dishonest"], answer: 0, explanation: "Honorable is a synonym of noble.", difficulty: "Medium" },
  { id: "s55", question: "Choose the synonym of 'Observe'.", options: ["Notice", "Ignore", "Forget", "Hide"], answer: 0, explanation: "Notice means to observe.", difficulty: "Medium" },
  { id: "s56", question: "Choose the synonym of 'Permanent'.", options: ["Temporary", "Lasting", "Brief", "Short"], answer: 1, explanation: "Lasting means permanent.", difficulty: "Medium" },
  { id: "s57", question: "Choose the synonym of 'Predict'.", options: ["Guess", "Forget", "Hide", "Avoid"], answer: 0, explanation: "Guess can be a synonym of predict.", difficulty: "Medium" },
  { id: "s58", question: "Choose the synonym of 'Rapid'.", options: ["Fast", "Slow", "Heavy", "Weak"], answer: 0, explanation: "Fast means rapid.", difficulty: "Medium" },
  { id: "s59", question: "Choose the synonym of 'Scarce'.", options: ["Rare", "Abundant", "Common", "Plentiful"], answer: 0, explanation: "Rare means scarce.", difficulty: "Medium" },
  { id: "s60", question: "Choose the synonym of 'Tidy'.", options: ["Messy", "Neat", "Dirty", "Untidy"], answer: 1, explanation: "Neat means tidy and organized.", difficulty: "Medium" },
  { id: "s61", question: "Choose the synonym of 'Unique'.", options: ["Ordinary", "Distinctive", "Common", "Typical"], answer: 1, explanation: "Distinctive means unique and different from others.", difficulty: "Medium" },
  { id: "s62", question: "Choose the synonym of 'Valuable'.", options: ["Worthless", "Precious", "Cheap", "Broken"], answer: 1, explanation: "Precious means highly valuable.", difficulty: "Medium" },
  { id: "s63", question: "Choose the synonym of 'Visible'.", options: ["Hidden", "Noticeable", "Dark", "Invisible"], answer: 1, explanation: "Noticeable means able to be seen.", difficulty: "Medium" },
  { id: "s64", question: "Choose the synonym of 'Weary'.", options: ["Energetic", "Tired", "Excited", "Active"], answer: 1, explanation: "Tired is a synonym of weary.", difficulty: "Medium" },
  { id: "s65", question: "Choose the synonym of 'Yield'.", options: ["Produce", "Destroy", "Waste", "Lose"], answer: 0, explanation: "Yield means to produce or generate.", difficulty: "Medium" },
  { id: "s66", question: "Choose the synonym of 'Zealous'.", options: ["Enthusiastic", "Lazy", "Careless", "Bored"], answer: 0, explanation: "Zealous means enthusiastic and passionate.", difficulty: "Medium" },
  { id: "s67", question: "Choose the synonym of 'Acquire'.", options: ["Lose", "Obtain", "Destroy", "Forget"], answer: 1, explanation: "Obtain means to acquire.", difficulty: "Hard" },
  { id: "s68", question: "Choose the synonym of 'Ancient'.", options: ["Modern", "Primitive", "Future", "Current"], answer: 1, explanation: "Primitive can be used as a synonym for ancient in some contexts.", difficulty: "Hard" },
  { id: "s69", question: "Choose the synonym of 'Benefit'.", options: ["Advantage", "Loss", "Damage", "Problem"], answer: 0, explanation: "Advantage is a synonym of benefit.", difficulty: "Hard" },
  { id: "s70", question: "Choose the synonym of 'Courage'.", options: ["Fear", "Bravery", "Weakness", "Cowardice"], answer: 1, explanation: "Bravery means courage.", difficulty: "Hard" },
  { id: "s71", question: "Choose the synonym of 'Decline'.", options: ["Refuse", "Accept", "Approve", "Support"], answer: 0, explanation: "Refuse is a synonym of decline.", difficulty: "Hard" },
  { id: "s72", question: "Choose the synonym of 'Efficient'.", options: ["Productive", "Wasteful", "Slow", "Lazy"], answer: 0, explanation: "Productive means efficient.", difficulty: "Hard" },
  { id: "s73", question: "Choose the synonym of 'Flexible'.", options: ["Rigid", "Adaptable", "Hard", "Fixed"], answer: 1, explanation: "Adaptable is a synonym of flexible.", difficulty: "Hard" },
  { id: "s74", question: "Choose the synonym of 'Generous'.", options: ["Charitable", "Selfish", "Greedy", "Mean"], answer: 0, explanation: "Charitable means generous in giving.", difficulty: "Hard" },
  { id: "s75", question: "Choose the synonym of 'Hostile'.", options: ["Friendly", "Aggressive", "Kind", "Helpful"], answer: 1, explanation: "Aggressive is a synonym of hostile.", difficulty: "Hard" },
  { id: "s76", question: "Choose the synonym of 'Important'.", options: ["Significant", "Trivial", "Minor", "Small"], answer: 0, explanation: "Significant means important.", difficulty: "Hard" },
  { id: "s77", question: "Choose the synonym of 'Journey'.", options: ["Voyage", "Stop", "Arrival", "Delay"], answer: 0, explanation: "Voyage is a synonym of journey.", difficulty: "Hard" },
  { id: "s78", question: "Choose the synonym of 'Kind'.", options: ["Compassionate", "Cruel", "Rude", "Harsh"], answer: 0, explanation: "Compassionate means kind and caring.", difficulty: "Hard" },
  { id: "s79", question: "Choose the synonym of 'Loyal'.", options: ["Faithful", "Dishonest", "False", "Unreliable"], answer: 0, explanation: "Faithful means loyal.", difficulty: "Hard" },
  { id: "s80", question: "Choose the synonym of 'Mend'.", options: ["Repair", "Break", "Damage", "Destroy"], answer: 0, explanation: "Repair is a synonym of mend.", difficulty: "Hard" },
  { id: "s81", question: "Choose the synonym of 'Modest'.", options: ["Humble", "Proud", "Arrogant", "Boastful"], answer: 0, explanation: "Humble is a synonym of modest.", difficulty: "Hard" },
  { id: "s82", question: "Choose the synonym of 'Neglect'.", options: ["Ignore", "Protect", "Care", "Support"], answer: 0, explanation: "Ignore is a synonym of neglect.", difficulty: "Hard" },
  { id: "s83", question: "Choose the synonym of 'Optimistic'.", options: ["Hopeful", "Negative", "Sad", "Pessimistic"], answer: 0, explanation: "Hopeful means optimistic about the future.", difficulty: "Hard" },
  { id: "s84", question: "Choose the synonym of 'Permit'.", options: ["Allow", "Forbid", "Prevent", "Reject"], answer: 0, explanation: "Allow is a synonym of permit.", difficulty: "Hard" },
  { id: "s85", question: "Choose the synonym of 'Quiet'.", options: ["Silent", "Loud", "Noisy", "Talkative"], answer: 0, explanation: "Silent is a synonym of quiet.", difficulty: "Hard" },
  { id: "s86", question: "Choose the synonym of 'Reject'.", options: ["Decline", "Accept", "Approve", "Support"], answer: 0, explanation: "Decline means to reject.", difficulty: "Hard" },
  { id: "s87", question: "Choose the synonym of 'Strength'.", options: ["Power", "Weakness", "Fear", "Failure"], answer: 0, explanation: "Power is a synonym of strength.", difficulty: "Hard" },
  { id: "s88", question: "Choose the synonym of 'Transparent'.", options: ["Clear", "Opaque", "Dark", "Hidden"], answer: 0, explanation: "Clear is a synonym of transparent.", difficulty: "Hard" },
  { id: "s89", question: "Choose the synonym of 'Urgent'.", options: ["Critical", "Unimportant", "Optional", "Delayed"], answer: 0, explanation: "Critical can mean urgent and requiring immediate attention.", difficulty: "Hard" },
  { id: "s90", question: "Choose the synonym of 'Victory'.", options: ["Success", "Failure", "Defeat", "Loss"], answer: 0, explanation: "Success is a synonym of victory.", difficulty: "Hard" },
  { id: "s91", question: "Choose the synonym of 'Wise'.", options: ["Sensible", "Foolish", "Ignorant", "Careless"], answer: 0, explanation: "Sensible is a synonym of wise.", difficulty: "Hard" },
  { id: "s92", question: "Choose the synonym of 'Abnormal'.", options: ["Unusual", "Normal", "Regular", "Common"], answer: 0, explanation: "Unusual is a synonym of abnormal.", difficulty: "Hard" },
  { id: "s93", question: "Choose the synonym of 'Conceal'.", options: ["Hide", "Reveal", "Display", "Expose"], answer: 0, explanation: "Hide is a synonym of conceal.", difficulty: "Hard" },
  { id: "s94", question: "Choose the synonym of 'Diminish'.", options: ["Reduce", "Increase", "Expand", "Grow"], answer: 0, explanation: "Reduce is a synonym of diminish.", difficulty: "Hard" },
  { id: "s95", question: "Choose the synonym of 'Endless'.", options: ["Infinite", "Limited", "Finite", "Restricted"], answer: 0, explanation: "Infinite means endless.", difficulty: "Hard" },
  { id: "s96", question: "Choose the synonym of 'Forbid'.", options: ["Prohibit", "Allow", "Permit", "Approve"], answer: 0, explanation: "Prohibit is a synonym of forbid.", difficulty: "Hard" },
  { id: "s97", question: "Choose the synonym of 'Gather'.", options: ["Collect", "Scatter", "Separate", "Divide"], answer: 0, explanation: "Collect is a synonym of gather.", difficulty: "Hard" },
  { id: "s98", question: "Choose the synonym of 'Hazard'.", options: ["Danger", "Safety", "Protection", "Benefit"], answer: 0, explanation: "Danger is a synonym of hazard.", difficulty: "Hard" },
  { id: "s99", question: "Choose the synonym of 'Invent'.", options: ["Create", "Destroy", "Copy", "Erase"], answer: 0, explanation: "Create is a synonym of invent.", difficulty: "Hard" },
  { id: "s100", question: "Choose the synonym of 'Justice'.", options: ["Fairness", "Corruption", "Crime", "Bias"], answer: 0, explanation: "Fairness is a synonym of justice.", difficulty: "Hard" },
];

const antonyms: Question[] = [
  { id: "a1", question: "Choose the antonym of 'Happy'.", options: ["Joyful", "Cheerful", "Sad", "Excited"], answer: 2, explanation: "Sad is the opposite of happy.", difficulty: "Easy" },
  { id: "a2", question: "Choose the antonym of 'Brave'.", options: ["Fearless", "Bold", "Cowardly", "Strong"], answer: 2, explanation: "Cowardly means lacking courage.", difficulty: "Easy" },
  { id: "a3", question: "Choose the antonym of 'Ancient'.", options: ["Historic", "Modern", "Old", "Primitive"], answer: 1, explanation: "Modern is the opposite of ancient.", difficulty: "Easy" },
  { id: "a4", question: "Choose the antonym of 'Expand'.", options: ["Grow", "Stretch", "Contract", "Increase"], answer: 2, explanation: "Contract means to become smaller.", difficulty: "Easy" },
  { id: "a5", question: "Choose the antonym of 'Generous'.", options: ["Kind", "Charitable", "Greedy", "Helpful"], answer: 2, explanation: "Greedy means unwilling to share.", difficulty: "Easy" },
  { id: "a6", question: "Choose the antonym of 'Victory'.", options: ["Success", "Achievement", "Defeat", "Triumph"], answer: 2, explanation: "Defeat is the opposite of victory.", difficulty: "Easy" },
  { id: "a7", question: "Choose the antonym of 'Permanent'.", options: ["Lasting", "Temporary", "Stable", "Enduring"], answer: 1, explanation: "Temporary means not permanent.", difficulty: "Easy" },
  { id: "a8", question: "Choose the antonym of 'Increase'.", options: ["Grow", "Expand", "Reduce", "Multiply"], answer: 2, explanation: "Reduce means to decrease.", difficulty: "Easy" },
  { id: "a9", question: "Choose the antonym of 'Accept'.", options: ["Receive", "Reject", "Approve", "Welcome"], answer: 1, explanation: "Reject means to refuse.", difficulty: "Easy" },
  { id: "a10", question: "Choose the antonym of 'Optimistic'.", options: ["Hopeful", "Positive", "Pessimistic", "Confident"], answer: 2, explanation: "Pessimistic means expecting negative outcomes.", difficulty: "Easy" },
  { id: "a11", question: "Choose the antonym of 'Visible'.", options: ["Clear", "Noticeable", "Invisible", "Obvious"], answer: 2, explanation: "Invisible means unable to be seen.", difficulty: "Easy" },
  { id: "a12", question: "Choose the antonym of 'Honest'.", options: ["Truthful", "Dishonest", "Reliable", "Sincere"], answer: 1, explanation: "Dishonest is the opposite of honest.", difficulty: "Easy" },
  { id: "a13", question: "Choose the antonym of 'Include'.", options: ["Contain", "Exclude", "Add", "Accept"], answer: 1, explanation: "Exclude means to leave out.", difficulty: "Easy" },
  { id: "a14", question: "Choose the antonym of 'Maximum'.", options: ["Highest", "Greatest", "Minimum", "Largest"], answer: 2, explanation: "Minimum is the opposite of maximum.", difficulty: "Easy" },
  { id: "a15", question: "Choose the antonym of 'Noisy'.", options: ["Loud", "Silent", "Busy", "Active"], answer: 1, explanation: "Silent means making little or no sound.", difficulty: "Easy" },
  { id: "a16", question: "Choose the antonym of 'Reward'.", options: ["Prize", "Benefit", "Punishment", "Gift"], answer: 2, explanation: "Punishment is the opposite of reward.", difficulty: "Easy" },
  { id: "a17", question: "Choose the antonym of 'Strength'.", options: ["Power", "Weakness", "Energy", "Force"], answer: 1, explanation: "Weakness is the opposite of strength.", difficulty: "Easy" },
  { id: "a18", question: "Choose the antonym of 'Wealthy'.", options: ["Rich", "Prosperous", "Poor", "Affluent"], answer: 2, explanation: "Poor is the opposite of wealthy.", difficulty: "Easy" },
  { id: "a19", question: "Choose the antonym of 'Arrive'.", options: ["Reach", "Appear", "Depart", "Enter"], answer: 2, explanation: "Depart means to leave.", difficulty: "Easy" },
  { id: "a20", question: "Choose the antonym of 'Artificial'.", options: ["Fake", "Natural", "Synthetic", "Man-made"], answer: 1, explanation: "Natural is the opposite of artificial.", difficulty: "Easy" },
  { id: "a21", question: "Choose the antonym of 'Ancient'.", options: ["Old", "Historic", "Modern", "Primitive"], answer: 2, explanation: "Modern refers to the present or recent times.", difficulty: "Easy" },
  { id: "a22", question: "Choose the antonym of 'Ascend'.", options: ["Climb", "Rise", "Descend", "Lift"], answer: 2, explanation: "Descend means to move downward.", difficulty: "Easy" },
  { id: "a23", question: "Choose the antonym of 'Bold'.", options: ["Fearless", "Timid", "Confident", "Brave"], answer: 1, explanation: "Timid means shy or lacking courage.", difficulty: "Easy" },
  { id: "a24", question: "Choose the antonym of 'Combine'.", options: ["Merge", "Join", "Separate", "Unite"], answer: 2, explanation: "Separate means to divide into parts.", difficulty: "Easy" },
  { id: "a25", question: "Choose the antonym of 'Dangerous'.", options: ["Risky", "Hazardous", "Safe", "Unsafe"], answer: 2, explanation: "Safe means free from danger.", difficulty: "Easy" },
  { id: "a26", question: "Choose the antonym of 'Defend'.", options: ["Protect", "Guard", "Attack", "Support"], answer: 2, explanation: "Attack means to act aggressively against.", difficulty: "Easy" },
  { id: "a27", question: "Choose the antonym of 'Early'.", options: ["Prompt", "Late", "Timely", "Quick"], answer: 1, explanation: "Late means after the expected time.", difficulty: "Easy" },
  { id: "a28", question: "Choose the antonym of 'Empty'.", options: ["Vacant", "Full", "Hollow", "Blank"], answer: 1, explanation: "Full means containing as much as possible.", difficulty: "Easy" },
  { id: "a29", question: "Choose the antonym of 'Famous'.", options: ["Popular", "Unknown", "Celebrated", "Renowned"], answer: 1, explanation: "Unknown means not widely recognized.", difficulty: "Easy" },
  { id: "a30", question: "Choose the antonym of 'Flexible'.", options: ["Adaptable", "Elastic", "Rigid", "Bendable"], answer: 2, explanation: "Rigid means stiff and not flexible.", difficulty: "Easy" },
  { id: "a31", question: "Choose the antonym of 'Generous'.", options: ["Kind", "Helpful", "Selfish", "Charitable"], answer: 2, explanation: "Selfish means concerned mainly with oneself.", difficulty: "Easy" },
  { id: "a32", question: "Choose the antonym of 'Humble'.", options: ["Modest", "Arrogant", "Polite", "Respectful"], answer: 1, explanation: "Arrogant means having excessive pride.", difficulty: "Easy" },
  { id: "a33", question: "Choose the antonym of 'Increase'.", options: ["Grow", "Expand", "Decrease", "Rise"], answer: 2, explanation: "Decrease means to become smaller.", difficulty: "Easy" },
  { id: "a34", question: "Choose the antonym of 'Junior'.", options: ["Young", "Senior", "Small", "Minor"], answer: 1, explanation: "Senior refers to a higher or older rank.", difficulty: "Medium" },
  { id: "a35", question: "Choose the antonym of 'Knowledge'.", options: ["Wisdom", "Learning", "Ignorance", "Education"], answer: 2, explanation: "Ignorance means lack of knowledge.", difficulty: "Medium" },
  { id: "a36", question: "Choose the antonym of 'Liberty'.", options: ["Freedom", "Independence", "Captivity", "Choice"], answer: 2, explanation: "Captivity means being imprisoned or confined.", difficulty: "Medium" },
  { id: "a37", question: "Choose the antonym of 'Major'.", options: ["Important", "Primary", "Minor", "Significant"], answer: 2, explanation: "Minor means lesser in importance.", difficulty: "Medium" },
  { id: "a38", question: "Choose the antonym of 'Natural'.", options: ["Organic", "Artificial", "Real", "Genuine"], answer: 1, explanation: "Artificial means made by humans.", difficulty: "Medium" },
  { id: "a39", question: "Choose the antonym of 'Optimistic'.", options: ["Positive", "Hopeful", "Pessimistic", "Confident"], answer: 2, explanation: "Pessimistic means expecting bad outcomes.", difficulty: "Medium" },
  { id: "a40", question: "Choose the antonym of 'Permanent'.", options: ["Lasting", "Stable", "Temporary", "Enduring"], answer: 2, explanation: "Temporary means lasting for a limited period.", difficulty: "Medium" },
  { id: "a41", question: "Choose the antonym of 'Ancient'.", options: ["Historic", "Modern", "Old", "Primitive"], answer: 1, explanation: "Modern means relating to the present time.", difficulty: "Medium" },
  { id: "a42", question: "Choose the antonym of 'Brilliant'.", options: ["Intelligent", "Dull", "Bright", "Talented"], answer: 1, explanation: "Dull means lacking brightness or intelligence.", difficulty: "Medium" },
  { id: "a43", question: "Choose the antonym of 'Construct'.", options: ["Build", "Create", "Destroy", "Develop"], answer: 2, explanation: "Destroy means to ruin or demolish.", difficulty: "Medium" },
  { id: "a44", question: "Choose the antonym of 'Delight'.", options: ["Joy", "Pleasure", "Misery", "Happiness"], answer: 2, explanation: "Misery is a state of great unhappiness.", difficulty: "Medium" },
  { id: "a45", question: "Choose the antonym of 'Expand'.", options: ["Grow", "Increase", "Contract", "Stretch"], answer: 2, explanation: "Contract means to become smaller.", difficulty: "Medium" },
  { id: "a46", question: "Choose the antonym of 'Faithful'.", options: ["Loyal", "Reliable", "Disloyal", "Trustworthy"], answer: 2, explanation: "Disloyal means not faithful.", difficulty: "Medium" },
  { id: "a47", question: "Choose the antonym of 'Gentle'.", options: ["Kind", "Soft", "Harsh", "Mild"], answer: 2, explanation: "Harsh means rough or severe.", difficulty: "Medium" },
  { id: "a48", question: "Choose the antonym of 'Harmony'.", options: ["Peace", "Agreement", "Conflict", "Unity"], answer: 2, explanation: "Conflict means disagreement or struggle.", difficulty: "Medium" },
  { id: "a49", question: "Choose the antonym of 'Inferior'.", options: ["Lower", "Superior", "Weaker", "Poorer"], answer: 1, explanation: "Superior means higher in quality or rank.", difficulty: "Medium" },
  { id: "a50", question: "Choose the antonym of 'Joyful'.", options: ["Happy", "Cheerful", "Miserable", "Delighted"], answer: 2, explanation: "Miserable means very unhappy.", difficulty: "Medium" },
  { id: "a51", question: "Choose the antonym of 'Kind'.", options: ["Helpful", "Compassionate", "Cruel", "Friendly"], answer: 2, explanation: "Cruel means causing pain or suffering.", difficulty: "Medium" },
  { id: "a52", question: "Choose the antonym of 'Legal'.", options: ["Lawful", "Valid", "Illegal", "Authorized"], answer: 2, explanation: "Illegal means against the law.", difficulty: "Medium" },
  { id: "a53", question: "Choose the antonym of 'Maximum'.", options: ["Greatest", "Highest", "Minimum", "Largest"], answer: 2, explanation: "Minimum is the smallest amount.", difficulty: "Medium" },
  { id: "a54", question: "Choose the antonym of 'Narrow'.", options: ["Slim", "Wide", "Thin", "Small"], answer: 1, explanation: "Wide means having a large distance across.", difficulty: "Medium" },
  { id: "a55", question: "Choose the antonym of 'Obedient'.", options: ["Respectful", "Disobedient", "Polite", "Loyal"], answer: 1, explanation: "Disobedient means refusing to obey.", difficulty: "Medium" },
  { id: "a56", question: "Choose the antonym of 'Polite'.", options: ["Respectful", "Courteous", "Rude", "Civil"], answer: 2, explanation: "Rude means impolite or offensive.", difficulty: "Medium" },
  { id: "a57", question: "Choose the antonym of 'Qualified'.", options: ["Eligible", "Competent", "Unqualified", "Skilled"], answer: 2, explanation: "Unqualified means lacking the necessary skills.", difficulty: "Medium" },
  { id: "a58", question: "Choose the antonym of 'Regular'.", options: ["Normal", "Routine", "Irregular", "Usual"], answer: 2, explanation: "Irregular means not following a pattern.", difficulty: "Medium" },
  { id: "a59", question: "Choose the antonym of 'Scarce'.", options: ["Rare", "Limited", "Abundant", "Insufficient"], answer: 2, explanation: "Abundant means existing in large quantities.", difficulty: "Medium" },
  { id: "a60", question: "Choose the antonym of 'Temporary'.", options: ["Brief", "Short-lived", "Permanent", "Limited"], answer: 2, explanation: "Permanent means lasting indefinitely.", difficulty: "Medium" },
  { id: "a61", question: "Choose the antonym of 'Abundant'.", options: ["Plentiful", "Numerous", "Scarce", "Ample"], answer: 2, explanation: "Scarce means available in small quantities.", difficulty: "Hard" },
  { id: "a62", question: "Choose the antonym of 'Accurate'.", options: ["Precise", "Correct", "Inaccurate", "Exact"], answer: 2, explanation: "Inaccurate means not correct.", difficulty: "Hard" },
  { id: "a63", question: "Choose the antonym of 'Active'.", options: ["Energetic", "Busy", "Inactive", "Lively"], answer: 2, explanation: "Inactive means not active.", difficulty: "Hard" },
  { id: "a64", question: "Choose the antonym of 'Admire'.", options: ["Respect", "Appreciate", "Despise", "Praise"], answer: 2, explanation: "Despise means to strongly dislike.", difficulty: "Hard" },
  { id: "a65", question: "Choose the antonym of 'Advantage'.", options: ["Benefit", "Gain", "Disadvantage", "Profit"], answer: 2, explanation: "Disadvantage means an unfavorable condition.", difficulty: "Hard" },
  { id: "a66", question: "Choose the antonym of 'Ancient'.", options: ["Historic", "Primitive", "Modern", "Traditional"], answer: 2, explanation: "Modern refers to the present time.", difficulty: "Hard" },
  { id: "a67", question: "Choose the antonym of 'Appear'.", options: ["Show", "Emerge", "Disappear", "Arrive"], answer: 2, explanation: "Disappear means to cease being visible.", difficulty: "Hard" },
  { id: "a68", question: "Choose the antonym of 'Artificial'.", options: ["Synthetic", "Fake", "Natural", "Manufactured"], answer: 2, explanation: "Natural means existing in nature.", difficulty: "Hard" },
  { id: "a69", question: "Choose the antonym of 'Assemble'.", options: ["Gather", "Meet", "Disperse", "Collect"], answer: 2, explanation: "Disperse means to scatter.", difficulty: "Hard" },
  { id: "a70", question: "Choose the antonym of 'Attack'.", options: ["Assault", "Strike", "Defend", "Charge"], answer: 2, explanation: "Defend means to protect.", difficulty: "Hard" },
  { id: "a71", question: "Choose the antonym of 'Beautiful'.", options: ["Pretty", "Attractive", "Ugly", "Lovely"], answer: 2, explanation: "Ugly means unpleasant in appearance.", difficulty: "Hard" },
  { id: "a72", question: "Choose the antonym of 'Benefit'.", options: ["Advantage", "Profit", "Harm", "Gain"], answer: 2, explanation: "Harm means damage or injury.", difficulty: "Hard" },
  { id: "a73", question: "Choose the antonym of 'Borrow'.", options: ["Take", "Receive", "Lend", "Use"], answer: 2, explanation: "Lend is the opposite of borrow.", difficulty: "Hard" },
  { id: "a74", question: "Choose the antonym of 'Certain'.", options: ["Sure", "Confident", "Uncertain", "Positive"], answer: 2, explanation: "Uncertain means not sure.", difficulty: "Hard" },
  { id: "a75", question: "Choose the antonym of 'Complex'.", options: ["Complicated", "Difficult", "Simple", "Detailed"], answer: 2, explanation: "Simple means easy to understand.", difficulty: "Hard" },
  { id: "a76", question: "Choose the antonym of 'Create'.", options: ["Build", "Produce", "Destroy", "Design"], answer: 2, explanation: "Destroy means to ruin completely.", difficulty: "Hard" },
  { id: "a77", question: "Choose the antonym of 'Cruel'.", options: ["Harsh", "Mean", "Kind", "Brutal"], answer: 2, explanation: "Kind means caring and considerate.", difficulty: "Hard" },
  { id: "a78", question: "Choose the antonym of 'Departure'.", options: ["Leaving", "Exit", "Arrival", "Journey"], answer: 2, explanation: "Arrival means reaching a destination.", difficulty: "Hard" },
  { id: "a79", question: "Choose the antonym of 'Difficult'.", options: ["Hard", "Challenging", "Easy", "Tough"], answer: 2, explanation: "Easy means requiring little effort.", difficulty: "Hard" },
  { id: "a80", question: "Choose the antonym of 'Encourage'.", options: ["Support", "Motivate", "Discourage", "Inspire"], answer: 2, explanation: "Discourage means to reduce confidence or enthusiasm.", difficulty: "Hard" },
  { id: "a81", question: "Choose the antonym of 'Entrance'.", options: ["Entry", "Arrival", "Exit", "Gateway"], answer: 2, explanation: "Exit means a way out.", difficulty: "Hard" },
  { id: "a82", question: "Choose the antonym of 'Expand'.", options: ["Grow", "Stretch", "Shrink", "Develop"], answer: 2, explanation: "Shrink means to become smaller.", difficulty: "Hard" },
  { id: "a83", question: "Choose the antonym of 'External'.", options: ["Outside", "Outer", "Internal", "Surface"], answer: 2, explanation: "Internal means inside.", difficulty: "Hard" },
  { id: "a84", question: "Choose the antonym of 'Failure'.", options: ["Defeat", "Loss", "Success", "Mistake"], answer: 2, explanation: "Success means achieving a desired result.", difficulty: "Hard" },
  { id: "a85", question: "Choose the antonym of 'False'.", options: ["Wrong", "Incorrect", "True", "Fake"], answer: 2, explanation: "True means in accordance with fact.", difficulty: "Hard" },
  { id: "a86", question: "Choose the antonym of 'Forgive'.", options: ["Pardon", "Excuse", "Blame", "Accept"], answer: 2, explanation: "Blame means to hold responsible for a fault.", difficulty: "Hard" },
  { id: "a87", question: "Choose the antonym of 'Friend'.", options: ["Companion", "Ally", "Enemy", "Partner"], answer: 2, explanation: "Enemy means a person who is opposed to another.", difficulty: "Hard" },
  { id: "a88", question: "Choose the antonym of 'Generous'.", options: ["Kind", "Helpful", "Stingy", "Charitable"], answer: 2, explanation: "Stingy means unwilling to spend or share.", difficulty: "Hard" },
  { id: "a89", question: "Choose the antonym of 'Guilty'.", options: ["Responsible", "Culpable", "Innocent", "Wrong"], answer: 2, explanation: "Innocent means not guilty.", difficulty: "Hard" },
  { id: "a90", question: "Choose the antonym of 'Healthy'.", options: ["Fit", "Strong", "Sick", "Active"], answer: 2, explanation: "Sick means affected by illness.", difficulty: "Hard" },
  { id: "a91", question: "Choose the antonym of 'Import'.", options: ["Bring in", "Receive", "Export", "Acquire"], answer: 2, explanation: "Export means to send goods out of a country.", difficulty: "Hard" },
  { id: "a92", question: "Choose the antonym of 'Junior'.", options: ["Young", "Lower", "Senior", "Minor"], answer: 2, explanation: "Senior refers to a higher rank or age.", difficulty: "Hard" },
  { id: "a93", question: "Choose the antonym of 'Knowledge'.", options: ["Education", "Learning", "Ignorance", "Wisdom"], answer: 2, explanation: "Ignorance means lack of knowledge.", difficulty: "Hard" },
  { id: "a94", question: "Choose the antonym of 'Laugh'.", options: ["Smile", "Giggle", "Cry", "Enjoy"], answer: 2, explanation: "Cry is commonly treated as the opposite of laugh.", difficulty: "Hard" },
  { id: "a95", question: "Choose the antonym of 'Maximum'.", options: ["Greatest", "Highest", "Minimum", "Largest"], answer: 2, explanation: "Minimum means the smallest amount.", difficulty: "Hard" },
  { id: "a96", question: "Choose the antonym of 'Natural'.", options: ["Organic", "Real", "Artificial", "Genuine"], answer: 2, explanation: "Artificial means made by humans.", difficulty: "Hard" },
  { id: "a97", question: "Choose the antonym of 'Optimist'.", options: ["Positive thinker", "Hopeful person", "Pessimist", "Dreamer"], answer: 2, explanation: "A pessimist expects negative outcomes.", difficulty: "Hard" },
  { id: "a98", question: "Choose the antonym of 'Permanent'.", options: ["Enduring", "Stable", "Temporary", "Lasting"], answer: 2, explanation: "Temporary means lasting for a short period.", difficulty: "Hard" },
  { id: "a99", question: "Choose the antonym of 'Presence'.", options: ["Attendance", "Appearance", "Absence", "Arrival"], answer: 2, explanation: "Absence means not being present.", difficulty: "Hard" },
  { id: "a100", question: "Choose the antonym of 'Private'.", options: ["Personal", "Secret", "Public", "Confidential"], answer: 2, explanation: "Public means open or available to everyone.", difficulty: "Hard" },
];

const fillBlanks: Question[] = [
  { id: "f1", question: "She is good ___ mathematics.", options: ["in", "at", "on", "with"], answer: 1, explanation: "We say 'good at' a subject or skill.", difficulty: "Easy" },
  { id: "f2", question: "We arrived ___ the airport on time.", options: ["to", "in", "at", "on"], answer: 2, explanation: "We use 'at' with specific points like airports.", difficulty: "Easy" },
  { id: "f3", question: "The cat jumped ___ the table.", options: ["onto", "into", "in", "at"], answer: 0, explanation: "'Onto' indicates movement to a surface.", difficulty: "Medium" },
  { id: "f4", question: "He apologized ___ being late.", options: ["of", "about", "for", "to"], answer: 2, explanation: "We apologize 'for' something.", difficulty: "Medium" },
  { id: "f5", question: "I'm not familiar ___ this software.", options: ["of", "with", "to", "about"], answer: 1, explanation: "We say 'familiar with' something.", difficulty: "Medium" },
  { id: "f6", question: "She has a strong interest ___ astronomy.", options: ["on", "for", "in", "of"], answer: 2, explanation: "'Interest in' is the correct collocation.", difficulty: "Easy" },
  { id: "f7", question: "He's responsible ___ the entire team.", options: ["of", "for", "to", "with"], answer: 1, explanation: "We are 'responsible for' something or someone.", difficulty: "Medium" },
  { id: "f8", question: "The results are consistent ___ our hypothesis.", options: ["to", "with", "for", "of"], answer: 1, explanation: "'Consistent with' is the standard collocation.", difficulty: "Medium" },
  { id: "f9", question: "She insisted ___ paying the bill.", options: ["in", "for", "on", "to"], answer: 2, explanation: "'Insist on' something or doing something.", difficulty: "Medium" },
  { id: "f10", question: "They congratulated him ___ his promotion.", options: ["for", "on", "about", "with"], answer: 1, explanation: "We congratulate someone 'on' an achievement.", difficulty: "Easy" },
  { id: "f11", question: "I'm capable ___ handling this myself.", options: ["of", "for", "to", "in"], answer: 0, explanation: "'Capable of' + gerund is the correct form.", difficulty: "Easy" },
  { id: "f12", question: "He's been accused ___ stealing.", options: ["for", "of", "with", "about"], answer: 1, explanation: "Someone is accused 'of' a crime.", difficulty: "Medium" },
  { id: "f13", question: "She's married ___ a doctor.", options: ["with", "to", "by", "of"], answer: 1, explanation: "In English, you marry or are married 'to' someone.", difficulty: "Easy" },
  { id: "f14", question: "We must comply ___ the regulations.", options: ["to", "with", "for", "on"], answer: 1, explanation: "'Comply with' rules or regulations.", difficulty: "Hard" },
  { id: "f15", question: "He's known ___ his honesty.", options: ["by", "for", "of", "with"], answer: 1, explanation: "People are 'known for' their qualities.", difficulty: "Medium" },
];

const sentenceCorrection: Question[] = [
  { id: "sc1", question: "Find the correct version: 'Me and him went to the store.'", options: ["Me and him went to the store.", "Him and me went to the store.", "He and I went to the store.", "I and he went to the store."], answer: 2, explanation: "Use subject pronouns 'He and I' as the subject.", difficulty: "Medium" },
  { id: "sc2", question: "Find the correct version: 'There is many reasons to learn.'", options: ["There is many reasons to learn.", "There are many reasons to learn.", "There be many reasons to learn.", "There many reasons to learn."], answer: 1, explanation: "'Reasons' is plural, so use 'are'.", difficulty: "Easy" },
  { id: "sc3", question: "Find the correct version: 'She don't have no money.'", options: ["She don't have no money.", "She doesn't have no money.", "She doesn't have any money.", "She not has any money."], answer: 2, explanation: "Avoid double negatives; use 'doesn't have any'.", difficulty: "Medium" },
  { id: "sc4", question: "Find the correct version: 'The team are playing well.' (US English)", options: ["The team are playing well.", "The team is playing well.", "The team be playing well.", "Team is play well."], answer: 1, explanation: "In US English, collective nouns take singular verbs.", difficulty: "Hard" },
  { id: "sc5", question: "Find the correct version: 'I have went there before.'", options: ["I have went there before.", "I have gone there before.", "I has gone there before.", "I have go there before."], answer: 1, explanation: "Present perfect uses past participle 'gone'.", difficulty: "Easy" },
  { id: "sc6", question: "Find the correct version: 'He is more taller than me.'", options: ["He is more taller than me.", "He is taller than me.", "He is most tall than me.", "He is more tall than me."], answer: 1, explanation: "Don't double up comparatives: just 'taller'.", difficulty: "Easy" },
  { id: "sc7", question: "Find the correct version: 'The amount of people grew.'", options: ["The amount of people grew.", "The number of people grew.", "The amount of peoples grew.", "Amount of people grew."], answer: 1, explanation: "Use 'number' with countable nouns and 'amount' with uncountable.", difficulty: "Medium" },
  { id: "sc8", question: "Find the correct version: 'Between you and I, this is wrong.'", options: ["Between you and I, this is wrong.", "Between you and me, this is wrong.", "Between I and you, this is wrong.", "Among you and I, this is wrong."], answer: 1, explanation: "After prepositions, use object pronouns: 'between you and me'.", difficulty: "Hard" },
  { id: "sc9", question: "Find the correct version: 'Each of the boys have a bike.'", options: ["Each of the boys have a bike.", "Each of the boys has a bike.", "Each of the boy have a bike.", "Each of the boys having a bike."], answer: 1, explanation: "'Each' is singular and takes a singular verb.", difficulty: "Medium" },
  { id: "sc10", question: "Find the correct version: 'If I would have known, I would have called.'", options: ["If I would have known, I would have called.", "If I had known, I would have called.", "If I have known, I would have called.", "If I knew, I would have called."], answer: 1, explanation: "Third conditional: 'If + had + past participle, would have + past participle'.", difficulty: "Hard" },
  { id: "sc11", question: "Find the correct version: 'She is taller than him.'", options: ["She is taller than him.", "She is taller than he.", "She is taller than he is.", "Both A and C"], answer: 3, explanation: "Both informal ('than him') and formal ('than he is') are accepted.", difficulty: "Medium" },
  { id: "sc12", question: "Find the correct version: 'I could of done it.'", options: ["I could of done it.", "I could have done it.", "I could had done it.", "I could did it."], answer: 1, explanation: "'Could have' (often heard as 'could've'), never 'could of'.", difficulty: "Easy" },
];

const reading: Question[] = [
  { id: "r1", question: "Passage: 'Bees pollinate roughly one-third of the food we eat. Without them, many crops would fail.' — What is the main idea?", options: ["Bees make honey.", "Bees are vital to food production.", "Bees live in hives.", "Bees sting humans."], answer: 1, explanation: "The passage emphasizes the bees' role in food production.", difficulty: "Easy" },
  { id: "r2", question: "Passage: 'Despite the rain, the marathon proceeded as planned.' — What can we infer?", options: ["The marathon was cancelled.", "The marathon was rescheduled.", "The marathon went on regardless of weather.", "The marathon was shortened."], answer: 2, explanation: "'Despite the rain' and 'proceeded as planned' indicate it continued.", difficulty: "Medium" },
  { id: "r3", question: "Passage: 'The novel's protagonist undergoes a profound transformation by the final chapter.' — What does 'protagonist' mean?", options: ["Antagonist", "Main character", "Narrator", "Author"], answer: 1, explanation: "The protagonist is the main character of a story.", difficulty: "Medium" },
  { id: "r4", question: "Passage: 'Although the experiment yielded inconclusive results, the team remained optimistic.' — Tone?", options: ["Pessimistic", "Hopeful", "Angry", "Indifferent"], answer: 1, explanation: "'Remained optimistic' signals a hopeful tone.", difficulty: "Hard" },
  { id: "r5", question: "Passage: 'Renewable energy sources are increasingly affordable.' — What does 'affordable' mean?", options: ["Expensive", "Reasonably priced", "Free", "Unavailable"], answer: 1, explanation: "Affordable means within someone's financial means.", difficulty: "Easy" },
  { id: "r6", question: "Passage: 'The CEO's resignation came as a bolt from the blue to investors.' — 'Bolt from the blue' suggests the news was:", options: ["Expected", "Sudden and surprising", "Welcome", "Slow to arrive"], answer: 1, explanation: "The idiom describes a completely unexpected event.", difficulty: "Medium" },
  { id: "r7", question: "Passage: 'While critics dismissed the film, audiences embraced it wholeheartedly.' — The relationship between critics and audiences is:", options: ["Identical", "Contrasting", "Complementary", "Unclear"], answer: 1, explanation: "'While' signals contrast between the two reactions.", difficulty: "Medium" },
  { id: "r8", question: "Passage: 'The new policy was ostensibly designed to help workers, but in practice it benefited only executives.' — 'Ostensibly' implies the stated purpose was:", options: ["Genuine", "Apparent but not real", "Hidden", "Obvious"], answer: 1, explanation: "'Ostensibly' suggests something appears true on the surface but may not be.", difficulty: "Hard" },
  { id: "r9", question: "Passage: 'Years of meticulous research culminated in a single, elegant equation.' — 'Culminated' means:", options: ["Began", "Reached a climax", "Failed", "Continued"], answer: 1, explanation: "'Culminate' means to reach a climax or end point.", difficulty: "Hard" },
  { id: "r10", question: "Passage: 'Solar panels have become commonplace on suburban rooftops.' — 'Commonplace' suggests they are now:", options: ["Rare", "Ordinary and widespread", "Forbidden", "Expensive"], answer: 1, explanation: "'Commonplace' means usual or ordinary.", difficulty: "Easy" },
];


export const categories: Category[] = [
  { slug: "grammar", name: "Grammar", description: "Master the rules that shape every sentence.", icon: "BookMarked", accent: "from-stone-700 to-stone-900", questions: grammar },
  { slug: "vocabulary", name: "Vocabulary", description: "Expand your word power with curated picks.", icon: "Feather", accent: "from-stone-700 to-stone-900", questions: vocabulary },
  { slug: "synonyms", name: "Synonyms", description: "Find the perfect word with similar meaning.", icon: "ArrowLeftRight", accent: "from-stone-700 to-stone-900", questions: synonyms },
  { slug: "antonyms", name: "Antonyms", description: "Identify opposites and sharpen contrast.", icon: "Repeat", accent: "from-stone-700 to-stone-900", questions: antonyms },
  { slug: "fill-blanks", name: "Fill the Blanks", description: "Complete sentences with the right word.", icon: "PenTool", accent: "from-stone-700 to-stone-900", questions: fillBlanks },
  { slug: "sentence-correction", name: "Sentence Correction", description: "Spot and fix grammatical errors.", icon: "SpellCheck", accent: "from-stone-700 to-stone-900", questions: sentenceCorrection },
  { slug: "reading", name: "Reading Comprehension", description: "Read passages and answer thoughtfully.", icon: "ScrollText", accent: "from-stone-700 to-stone-900", questions: reading },
  { slug: "mixed", name: "Mixed Practice", description: "A random blend from every category.", icon: "Library", accent: "from-stone-700 to-stone-900", questions: [] },
];

export function getCategory(slug: string): Category | undefined {
  if (slug === "mixed") {
    const all = categories.flatMap((c) => c.questions);
    return { ...categories.find((c) => c.slug === "mixed")!, questions: all };
  }
  return categories.find((c) => c.slug === slug);
}

export function getDailyQuestions(seed: string, count = 5): Question[] {
  const all = categories.flatMap((c) => c.questions);
  // simple deterministic shuffle using seed
  let h = 0;
  for (let i = 0; i < seed.length; i++) h = (h * 31 + seed.charCodeAt(i)) >>> 0;
  const rand = () => {
    h = (h * 1664525 + 1013904223) >>> 0;
    return h / 0xffffffff;
  };
  const arr = [...all];
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(rand() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr.slice(0, count);
}

export function shuffleQuestions<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}
