/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizCategoryRouteImport } from './routes/quiz.$category'

const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizCategoryRoute = QuizCategoryRouteImport.update({
  id: '/quiz/$category',
  path: '/quiz/$category',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/daily': typeof DailyRoute
  '/practice': typeof PracticeRoute
  '/results': typeof ResultsRoute
  '/quiz/$category': typeof QuizCategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/daily': typeof DailyRoute
  '/practice': typeof PracticeRoute
  '/results': typeof ResultsRoute
  '/quiz/$category': typeof QuizCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/daily': typeof DailyRoute
  '/practice': typeof PracticeRoute
  '/results': typeof ResultsRoute
  '/quiz/$category': typeof QuizCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/daily'
    | '/practice'
    | '/results'
    | '/quiz/$category'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/daily' | '/practice' | '/results' | '/quiz/$category'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/daily'
    | '/practice'
    | '/results'
    | '/quiz/$category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DailyRoute: typeof DailyRoute
  PracticeRoute: typeof PracticeRoute
  ResultsRoute: typeof ResultsRoute
  QuizCategoryRoute: typeof QuizCategoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$category': {
      id: '/quiz/$category'
      path: '/quiz/$category'
      fullPath: '/quiz/$category'
      preLoaderRoute: typeof QuizCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DailyRoute: DailyRoute,
  PracticeRoute: PracticeRoute,
  ResultsRoute: ResultsRoute,
  QuizCategoryRoute: QuizCategoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
